#pragma once

/* Stub version header for PlatformIO / embedded builds.
 * The real file is generated by CMake in a normal Codec2 build.
 */
#define CODEC2_VERSION_MAJOR 1
#define CODEC2_VERSION_MINOR 2
#define CODEC2_VERSION_PATCH 0
#define CODEC2_VERSION "1.2.0"